---
galaxy_info:
  author: George Miroshnykov
  description: Add all hosts from Ansible inventory to target's /etc/hosts
  company: Rebbix
  license: BSD
  min_ansible_version: 1.2

  platforms:
  - name: Ubuntu
    versions:
    - precise

  categories:
  - cloud
  - networking

dependencies: []
