---
galaxy_info:
  author: George Miroshnykov
  description: Setup Redis database
  min_ansible_version: 1.4
  platforms:
  - name: Ubuntu
    versions:
    - precise
  categories:
  - database
  - database:nosql
